/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xmass;

    import com.mysql.cj.jdbc.result.ResultSetMetaData;
    import java.util.HashSet;
    import java.util.Set;
    import java.sql.PreparedStatement;
    import java.sql.ResultSet;
    import java.sql.Connection;
    import java.sql.SQLException;
    import javax.swing.JOptionPane;
    import javax.swing.table.TableModel;
    import javax.swing.table.DefaultTableModel;
public class Registro_productos extends javax.swing.JInternalFrame {
    
    Base_Datos conSQ = new Base_Datos();

    DefaultTableModel dtm=new DefaultTableModel();
    
    public Registro_productos() {
        initComponents();
        
        try{
           juwu.setModel(dtm);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            Base_Datos bd = new Base_Datos();
            Connection con = bd.getConectarDB();
            
            String sql = "SELECT SKU, Nombre, Cantidad, Categoria, Precio FROM productos";
            ps= con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            
            dtm.addColumn("SKU");
            dtm.addColumn("Nombre");
            dtm.addColumn("Cantidad");
            dtm.addColumn("Categoria");
            dtm.addColumn("Precio");
            
            
            while(rs.next()){
                    
                Object[] filas = new Object[cantidadColumnas];
                
                for(int i = 0; i< cantidadColumnas; i++)
                {
                    filas[i] = rs.getObject(i + 1);
                }
                
                dtm.addRow(filas);
            }   
            
            
        } catch(Exception ex){
            System.err.println(ex.toString());
        }
        
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        jCantidad = new javax.swing.JTextField();
        jSKU = new javax.swing.JTextField();
        jCategoria = new javax.swing.JComboBox<>();
        bAgregar = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        juwu = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Registro de Productos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("SKU");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 30, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Categoria");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));
        getContentPane().add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 110, 30));

        jCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(jCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 110, 30));
        getContentPane().add(jSKU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 110, 30));

        jCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Congelados", "Lacteos", "Abarrotes", "Bebidas" }));
        getContentPane().add(jCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 110, 30));

        bAgregar.setText("Agregar");
        bAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(bAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 80, 30));

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });
        getContentPane().add(bEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 173, 80, 30));

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(bEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Precio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        getContentPane().add(jPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 110, 30));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 60, 110));

        juwu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        juwu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                juwuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(juwu);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 520, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarActionPerformed
        
        PreparedStatement ps = null;
        try {
            Base_Datos objCon = new Base_Datos();
            Connection conn = objCon.getConectarDB();
            ps = conn.prepareStatement("INSERT INTO productos (SKU, Nombre, Cantidad, categoria, Precio) VALUES (?,?,?,?,?)");
            ps.setString(1, jSKU.getText());
            ps.setString(2, jNombre.getText());
            ps.setString(3, jCantidad.getText());
            ps.setObject(4, jCategoria.getSelectedItem());
            ps.setString(5, jPrecio.getText());

            ps.execute();

            JOptionPane.showMessageDialog(null, "Producto Guardado");
            Object[] fila = new Object[5];
            fila[0] = jSKU.getText();
            fila[1] = jNombre.getText();
            fila[2] = jCantidad.getText();
            fila[3] = jCategoria.getSelectedItem();
            fila[4] = jPrecio.getText();
            dtm.addRow(fila);

            limpiar();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al Guardar Producto");
            System.out.println(ex);
        }
    

        
    }//GEN-LAST:event_bAgregarActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        
        PreparedStatement ps = null;
        try {

            Base_Datos objCon = new Base_Datos();
            Connection conn = objCon.getConectarDB();

            int Fila = juwu.getSelectedRow();
            String SKU = juwu.getValueAt(Fila, 0).toString();

            ps = conn.prepareStatement("DELETE FROM productos WHERE SKU=?");
            ps.setString(1, SKU);
            ps.execute();

            dtm.removeRow(Fila);
            JOptionPane.showMessageDialog(null, "Producto Eliminado");
            limpiar();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al Eliminar Producto");
            System.out.println(ex.toString());
        }
        
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        
       int Fila = juwu.getSelectedRow();

        PreparedStatement ps = null;
        try {
            Base_Datos objCon = new Base_Datos();
            Connection conn = objCon.getConectarDB();
            ps = conn.prepareStatement("UPDATE productos SET Nombre=?, Cantidad=?, Categoria=?, Precio=? WHERE SKU=?");

            ps.setString(1, jNombre.getText());
            ps.setString(2, jCantidad.getText());
            ps.setObject(3, jCategoria.getSelectedItem());
            ps.setString(4, jPrecio.getText());
            ps.setString(5, jSKU.getText());
            
            ps.execute();

            JOptionPane.showMessageDialog(null, "Producto Modificado");
            juwu.setValueAt(jSKU.getText(), Fila, 0);
            juwu.setValueAt(jNombre.getText(), Fila, 1);
            juwu.setValueAt(jCantidad.getText(), Fila, 2);
            juwu.setValueAt(jCategoria.getSelectedItem(), Fila, 3);
            juwu.setValueAt(jPrecio.getText(), Fila, 4);

            limpiar();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al Modificar Producto");
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_bEditarActionPerformed

    private void jCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCantidadActionPerformed

    private void juwuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juwuMouseClicked
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            Base_Datos objCon = new Base_Datos();
            Connection conn = objCon.getConectarDB();

            int Fila = juwu.getSelectedRow();
            String codigo = juwu.getValueAt(Fila, 0).toString();

            ps = conn.prepareStatement("SELECT SKU, Nombre, Cantidad, Categoria, Precio FROM productos WHERE SKU=?");
            ps.setString(1, codigo);
            rs = ps.executeQuery();

            while (rs.next()) {
                jSKU.setText(rs.getString("SKU"));
                jNombre.setText(rs.getString("Nombre"));
                jCantidad.setText(rs.getString("Cantidad"));
                jCategoria.setSelectedItem(rs.getString("Categoria"));
                jPrecio.setText(rs.getString("Precio"));
            }
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_juwuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JTextField jCantidad;
    private javax.swing.JComboBox<String> jCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNombre;
    private javax.swing.JTextField jPrecio;
    private javax.swing.JTextField jSKU;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable juwu;
    // End of variables declaration//GEN-END:variables

    
    private void limpiar() {
        jSKU.setText("");
        jNombre.setText("");
        jCantidad.setText("");
        jPrecio.setText("");
    }
}


